"""first

Revision ID: 08909f967463
Revises: 
Create Date: 2022-02-02 13:11:04.229863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '08909f967463'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=130), nullable=True),
    sa.Column('category', sa.Enum('Conference', 'Seminar', 'Congress', 'Course', name='eventtypes'), nullable=False),
    sa.Column('keeper_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('place', sa.String(length=140), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('is_face_to_face', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['keeper_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
